# Generated by Django 4.2.2 on 2023-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="choice_a",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="choice_b",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="choice_c",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="choice_d",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
